version: '3.7'
services:
  # mongo section
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 5005:27017
    networks: 
      - mongo
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 5004:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks: 
      - mongo
networks:
  mongo:
    driver: bridge