version: "3.9"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    environment:
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
    ports:
      - 5678:5678
    volumes:
      - ./storage:/home/node/.n8n
